open-cluster-management-io/governance-policy-propagator

Makefile
Signed-off-by: Mike Ng <ming@redhat.com>
closes https://github.com/open-cluster-management-io/community/issues/59
=> check if ns exists before create

Makefile
Signed-off-by: dongdwdw <dongdwdw@cn.ibm.com>
=> fix GOBIN issue for e2e test

README.md
Signed-off-by: wangglbj <wangglbj@cn.ibm.com> I have modified the previously incorrect [https://github.com/open-cluster-management-io/governance-policy-framework](url) link.  Dhaiducek, can you help me review it again,thanks
=> Modify the incorrect URL link in the README.md

.github/workflows/go-release.yml
The workflow will trigger on any tag pushed that looks like `v*.*.*`.
The action is based off of the one in the registration repo, but using
the build process in this repo.
=> Add a release workflow

CHANGELOG/CHANGELOG-v0.5.0.md
Since this is the first release for this repo, I did not fill in an
actual changelog. If we want to (in the future) we could use this file
as an initial feature list... but I don't think it's fully necessary.
Mostly this is so the auto-generated release doesn't have a broken link.
=> Add changelog for v0.5.0

.github/workflows/fossa.yml
- https://github.com/open-cluster-management/backlog/issues/18460
=> Add FOSSA scan

OWNERS, deploy/crds/external/tower.ansible.com_joblaunch_crd.yaml
Users that are not creating content for grc should be removed
Refs:
- https://github.com/stolostron/backlog/issues/21546
Signed-off-by: Gus Parvin <gparvin@redhat.com>
=> Remove user no longer in grc from owners

api/v1beta1/policyautomation_types.go, controllers/automation/policyMapper.go, controllers/automation/policyautomation_controller.go, controllers/common/ansible.go, deploy/crds/policy.open-cluster-management.io_policyautomations.yaml, test/e2e/case5_policy_automation_test.go, test/resources/case5_policy_automation/case5-policy-automation-disable.yaml, test/resources/case5_policy_automation/case5-policy-automation-everyEvent.yaml
https://github.com/open-cluster-management-io/enhancements/pull/60
=> Add an "everyEvent" Ansible Job Run Mode to the Policy addon

test/e2e/case5_policy_automation_test.go
https://github.com/open-cluster-management-io/governance-policy-propagator/pull/38#issuecomment-1196813082
=> Optimize-the-delayAfterRunSeconds-test-case-run-time

controllers/automation/policyautomation_controller.go
Current `trimmedTargetList` in `everyEvent` mode doesn't remove the duplicated cluster name
=> Remove the duplicated cluster name when creating Ansible job

api/v1beta1/policyautomation_types.go, controllers/common/ansible.go, deploy/crds/policy.open-cluster-management.io_policyautomations.yaml, test/e2e/case5_policy_automation_test.go, test/resources/case5_policy_automation/case5-policy-automation-everyEvent.yaml
https://github.com/stolostron/backlog/issues/20158
=> add job_ttl field to ansible job

controllers/encryptionkeys/encryptionkeys_controller.go, controllers/propagator/policy_controller.go, deploy/operator.yaml, deploy/rbac/role.yaml
This adds get, list, and watch on all resources for Hub policy templates. Additionally, there isn't a need for read/write access on all Secrets.
Related:
https://issues.redhat.com/browse/ACM-1911
=> Update the permissions to match what is needed

api/v1/policy_types.go, deploy/crds/policy.open-cluster-management.io_policies.yaml
Needed to set the Pending status on parent policies
=> Add Pending to complianceState enum

controllers/propagator/replication.go, controllers/propagator/replication_test.go
The new-ish functions are now tested (and fixed for problems the tests and reviewers found), and better documented. Hopefully some of the "fake" functions in the new tests can find some more use in the future.
=> Fix some issues in replication code

api/v1beta1/policyautomation_types.go, controllers/automation/policyautomation_controller.go, controllers/common/ansible.go, controllers/common/common.go, controllers/propagator/propagation.go, controllers/propagator/replication.go, deploy/crds/policy.open-cluster-management.io_policyautomations.yaml, test/e2e/case5_policy_automation_test.go, test/resources/case5_policy_automation/case5-test-policy.yaml
https://github.com/open-cluster-management-io/enhancements/pull/73
=> Provide PolicyViolationContext to Ansible Tower

api/v1beta1/policyautomation_types.go, deploy/crds/policy.open-cluster-management.io_policyautomations.yaml
https://github.com/stolostron/multiclusterhub-operator/pull/894
=> update policyViolationContextLimit kubebuilder validation

api/v1beta1/policyautomation_types.go, build/common/config/.golangci.yml, test/e2e/case5_policy_automation_test.go
=> update violationMessage field name

api/v1beta1/policyautomation_types.go, api/v1beta1/policyset_types.go, deploy/crds/policy.open-cluster-management.io_policyautomations.yaml, deploy/crds/policy.open-cluster-management.io_policysets.yaml
Missing descriptions in the CRD.
Refs:
- https://github.com/stolostron/backlog/issues/26528
Signed-off-by: Gus Parvin <gparvin@redhat.com>
=> Updates to the CRDs where some field descriptions are missing

controllers/automation/policyautomation_controller.go, test/e2e/case5_policy_automation_test.go
=> Add policy violation context for manual run model

controllers/propagator/propagation.go
Relates:
https://issues.redhat.com/browse/ACM-2397
=> Delete the propagation failure metric for deleted policies

build/Dockerfile
=> Clean up extra lines in Dockerfile

api/v1/policy_types.go, deploy/crds/kustomize/policy.open-cluster-management.io_policies.yaml, deploy/crds/policy.open-cluster-management.io_policies.yaml
Signed-off-by: Dale Haiducek <19750917+dhaiducek@users.noreply.github.com>
=> `PolicyDepenency` --> `PolicyDependency`

test/e2e/case14_root_policy_metrics_test.go
ref:
- https://issues.redhat.com/browse/ACM-2513
=> add test for ocm_handle_root_policy_duration metric

controllers/policymetrics/policymetrics_controller.go, main.go
In scale tests, the policy-metrics controller has bad latency since there is a reconcile per root or replicated policy status update. This was improved in PR #86, but it needs concurrency to be able to keep up.
Relates:
https://issues.redhat.com/browse/ACM-2543
=> Add concurrency to the policy-metrics controller

controllers/common/ansible.go, test/e2e/case5_policy_automation_test.go, test/resources/case5_policy_automation/case5-policy-automation-disable.yaml, test/resources/case5_policy_automation/case5-policy-automation-everyEvent.yaml
Refs:
- https://issues.redhat.com/browse/ACM-5093
=> Sanitize AnsibleJob name

build/Dockerfile
=> Bump Go in Dockerfile

Makefile, controllers/automation/policyPredicate.go, controllers/automation/policyautomation_controller.go, controllers/common/ansible.go, go.mod, test/e2e/case5_policy_automation_test.go, test/resources/managed3-cluster.yaml
Create a policy with disabled set to true. Then, create a policyAutomation with everyevent mode and "policyViolationLimits" set to 0.
Ref: https://issues.redhat.com/browse/ACM-4777
Signed-off-by: Yi Rae Kim <yikim@redhat.com>
=> Bug: Only one policy violation status was passed into ansiblejob 

build/common/scripts/gobuild.sh
=> Stop explicitly disabling CGO

Makefile
The 63 character limit validation for policy name is not working while creating a Policy via CLI.
Policy creation - Policy name + namespace name can’t go longer than 63 From CLI, it possible to create a policy with a name like “policy-check-setupjob-setupjob-operator-installer” with no issue; but, while wanting to edit it, we can’t.
Getting this error: “The combined length of namespace and policy nmabe (namespaceName.policyName) should not exceed 63 characters (see attached screenshot)
- Extend timeout 
- Add `make webhook` for framework tests 
Ref: https://issues.redhat.com/browse/ACM-3558
Signed-off-by: Yi Rae Kim [yikim@redhat.com](mailto:yikim@redhat.com)
=> Add webhook for limit 64 char and framework test fix

controllers/common/common.go, controllers/policyset/placementBindingPredicate.go, controllers/policyset/policyset_controller.go, controllers/propagator/placementBindingMapper.go, controllers/propagator/placementBindingPredicate.go, controllers/propagator/placementDecisionMapper.go, controllers/propagator/placementRuleMapper.go, controllers/propagator/policy_controller.go, controllers/propagator/propagation.go, controllers/rootpolicystatus/root_policy_status_controller.go
The first commit is a collection of small-ish things I noticed while looking for possible inefficiencies in the propagator. The second has the "meat" of this PR - read its commit message for more details.
While this PR might slightly improve the performance of the propagator, it's unlikely to be a major step forward.
=> Refactoring `getPolicyPlacementDecisions`

controllers/propagator/replicatepolicy_pb_eventHandler.go, test/e2e/case16_selective_policy_enforcement_test.go
To reduce the number of unnecessary reconciles on replicated policies, when a PlacementBinding is updated, only the added or removed policies are reconciled. However, this meant that when other fields are updated in a PlacementBinding, the affected policies were not being updated accordingly. Now, when there are other changes, all possibly affected replicated policies will be reconciled.
Refs:
- https://issues.redhat.com/browse/ACM-8515
=> Handle other changes to PlacementBinding

controllers/propagator/replication.go, main.go
See each commit for more details.
=> Modest Memory Improvements

api/v1/policy_webhook.go
I noticed we were logging every create/update of a Policy. This reduces the default logging to only validation errors. (Though I could be swayed to re-default the other logs 🙂 )
=> Tweak webhook logging

Makefile, controllers/complianceeventsapi/server.go, controllers/complianceeventsapi/types.go, test/e2e/case18_compliance_api_test.go
Relates:
https://issues.redhat.com/browse/ACM-6871
=> Add filtering options to the compliance events API

controllers/complianceeventsapi/migrations/000001_compliance_history_initial_tables.up.sql, controllers/complianceeventsapi/server.go, controllers/complianceeventsapi/types.go, controllers/complianceeventsapi/types_test.go, controllers/propagator/replicatedpolicy_controller_test.go, test/e2e/case18_compliance_api_test.go
See each commit for the changes.
=> Various small fixes for compliance history

controllers/complianceeventsapi/server.go
The SQL query is dynamically generated using prepared statements for user provided values.
=> Ignore false gosec violation

test/utils/utils.go
=> Include command in error from `kubectl` commands

controllers/complianceeventsapi/auth.go, controllers/complianceeventsapi/server.go, test/e2e/case18_compliance_api_test.go
See each commit for the details
=> Follow up PR for ACM-6866/#164

controllers/policyset/policyset_controller.go, test/e2e/case19_rep_policy_placement_test.go
Relates:
https://github.com/stolostron/backlog/issues/27491
=> Add more logging for when a placement binding can't be retrieved

controllers/complianceeventsapi/server.go, controllers/complianceeventsapi/types.go
Relates:
https://issues.redhat.com/browse/ACM-10180
=> Add additional log details for database errors

controllers/complianceeventsapi/server.go
This seems to be a quirk in the Go HTTP server when sending chunks where if there is more than one chunk, it seems to fallback to the content-type originally set. Before this commit, it was application/json.
=> Send the correct content-type header with a large CSV

controllers/complianceeventsapi/server.go
CSV get endpoint header is JSON content. This PR will set to `text/csv`
=> Fix csv Header json content issue

controllers/complianceeventsapi/server.go
There were a few spots that were missed in:
394307dd9ce553fdcab78dac8962c185173124ce
Relates:
https://issues.redhat.com/browse/ACM-10180
=> Add additional logs for database errors

.github/workflows/framework-kind.yml
ref: https://issues.redhat.com/browse/ACM-4811
=> Run framework tests on OCM PRs

controllers/complianceeventsapi/server.go, go.mod, go.sum, test/e2e/case18_compliance_api_test.go
A couple of other commits were snuck in this PR that are partially related.
Relates:
https://issues.redhat.com/browse/ACM-10898
https://github.com/stolostron/rbac-api-utils/pull/7
=> Update rbac-api-utils to handle partial SelfSubjectRulesReview success

deploy/crds/kustomize/ns-validation.json, deploy/crds/policy.open-cluster-management.io_policies.yaml, test/e2e/case15_dep_crd_validation_test.go
Delete iam-policy-controller trace in this repo
Ref: https://issues.redhat.com/browse/ACM-10859
=> Remove the IAM Policy Controller

.gitignore, .vscode/launch.json
Relates:
https://issues.redhat.com/browse/ACM-10885
=> Add a launch.json file for local development

controllers/policymetrics/metrics.go, controllers/policymetrics/policymetrics_controller.go
ref: https://issues.redhat.com/browse/ACM-11504
=> Add -1 as a possible compliance value for the status metric

Makefile, deploy/crds/policy.open-cluster-management.io_placementbindings.yaml, deploy/crds/policy.open-cluster-management.io_policyautomations.yaml, deploy/crds/policy.open-cluster-management.io_policysets.yaml
=> Make CRD descriptions folded (Pt 2)

api/v1beta1/policyautomation_types.go, deploy/crds/policy.open-cluster-management.io_policyautomations.yaml
Slack thread: https://redhat-internal.slack.com/archives/CU4QXLPQB/p1727683618630359
=> Update automation TTL description

api/v1beta1/policyautomation_types.go, deploy/crds/policy.open-cluster-management.io_policyautomations.yaml
ref: https://issues.redhat.com/browse/ACM-14657
=> Remove requirement for `eventHook` in automation

build/Dockerfile
=> Address `oauth2` vuln
