open-cluster-management-io/governance-policy-propagator

Makefile

Addresses open-cluster-management-io/community#58
Signed-off-by: Mike Ng <ming@redhat.com>

fix make test-dependencies by only perform 'mv' if kubebuilder doesn't t exist already

---

.github/workflows/go-release.yml

I believe it failed because the working directory was not where it
checked out the code. I updated the release steps to more closely match
the configuration of the post-submit job.

Fix release workflow

---

build/Dockerfile
build/template-delimiter.patch
deploy/crds/external/tower.ansible.com_joblaunch_crd.yaml

This backports the upstream fix to the text/template library. This is
required so that fields that start with the letter `h` can be accessed
within Hub policy templates.
The second commit is to fix the CI when running against the latest Kubernetes version.
Relates:
https://github.com/stolostron/backlog/issues/21440

Fix text/template so that it doesn't confuse the action for a delimiter

---

main.go

Switching to using leases instead of configmapsleases for leader
election
Refs:
- https://github.com/stolostron/backlog/issues/19110
Signed-off-by: Gus Parvin <gparvin@redhat.com>

Change leader election to use the leases resource

---

main.go

Updating go-template-utils causes the klog flags to not be initialized implicitly.

Initialize klog explicitly

---

controllers/common/common.go
controllers/propagator/propagation.go
controllers/propagator/replication_utils.go
test/e2e/case13_policyset_dependencies_test.go
test/e2e/case1_propagation_test.go
test/e2e/case3_mutation_recovery_test.go
test/resources/case13_policyset_dependencies/case13-resources.yaml
test/resources/case13_policyset_dependencies/policyset2.yaml
test/resources/case13_policyset_dependencies/policyset2update.yaml
test/resources/case13_policyset_dependencies/test1.yaml
test/resources/case13_policyset_dependencies/test2.yaml
test/resources/case13_policyset_dependencies/test3.yaml
test/resources/case13_policyset_dependencies/test4.yaml

Some refactoring to (I think) get things in better shape for the changes, and then this is the main commit message:
Since whether dependencies are satisfied will be calculated on the managed cluster, and since PolicySets are not propagated to managed clusters, in order to work "as expected" by a user, any PolicySet dependencies should be replaced with the Policies that are in that set.
To keep those lists up to date, the root policies need to reconcile whenever the dependent PolicySets are updated, accomplished here with the new dynamic watch library. So now Policies watch items referenced in their templates, as well as relevant PolicySets.
Note: when a PolicySet does not exist, the dependency is not changed - it is expected that the status message from the managed cluster (indicating …

Policyset dependencies

---

controllers/common/common.go
controllers/common/common_test.go
controllers/encryptionkeys/encryptionkeys_controller.go
controllers/policyset/policyset_controller.go
controllers/propagator/policyMapper.go
controllers/propagator/propagation.go
controllers/propagator/propagation_test.go

There were two places where the root-policy label was assumed to have one `.` in it, since that's how the propagator sets the label. But if a user created a Policy with that label, it doesn't necessarily have that character, so the propagator could panic trying to access a value out of the range of the slice.
There was another place that had the potential to have a similar issue, so a struct is now used instead of a string that needed to be split.
Refs:
- https://github.com/stolostron/backlog/issues/26592

Root policy label bug

---

controllers/propagator/policy_controller.go

The policy passed to cleanUpPolicy had invalid apiVersion field set. This caused the dynamic watch library not to clean up the watches.
Relates:
https://github.com/stolostron/backlog/issues/25866

Fix the dynamic watch cleanup

---

Makefile
controllers/propagator/metric.go
controllers/propagator/policy_controller.go
controllers/propagator/propagation.go
test/e2e/case12_encryptionkeys_controller_test.go
test/e2e/case14_templates_metrics_test.go

Adds a Gauge Vector that records the number of active watches for each root policy.
Addresses:
- https://github.com/stolostron/backlog/issues/25866

Add `hub_template_active_watches` metric

---

controllers/propagator/aggregation.go
controllers/propagator/aggregation_test.go
controllers/propagator/propagation.go
test/e2e/case2_aggregation_test.go
test/resources/case2_aggregation/managed-mixed-pending-compliant.yaml
test/resources/case2_aggregation/managed-mixed-pending-noncompliant.yaml
test/resources/case2_aggregation/managed-one-status-noncompliant.yaml

When a replicated policy is in the Pending state, and all others for that root policy are Compliant, then the root policy should be Pending.
This change extracts some other aggregation logic in a way that should be more testable, and adds unit tests for some previous existing behavior.
Refs:
- https://github.com/stolostron/backlog/issues/26182

Aggregate Pending status from replicated policies

---

controllers/policyset/policyset_controller.go
test/e2e/case11_policyset_controller_test.go
test/resources/case11_policyset_controller/case11-statuscheck-7.yaml
test/resources/case11_policyset_controller/case11-statuscheck-8.yaml

Allows the status of a `PolicySet` to be `pending`. The compliance state for the policy set follows the same rules as parent policies - if a policy set contains pending policies, the status will be pending unless there are noncompliant policies as well, in which case the policy set will be noncompliant.
The PR also changes the wording of the status message that shows up in a policy set when some policies in the set do not have a status. Previously it referred to those policies as pending, which could be easily confused with policies with the pending compliance state. In order to avoid this confusion, this PR changes the wording from pending policies to policies that are awaiting status.
Needed for https://issues.redhat.com/browse/ACM-2101 …

enable pending status for policy set

---

Makefile
deploy/crds/kustomize/kustomization.yaml
deploy/crds/kustomize/ns-validation.json
deploy/crds/kustomize/policy.open-cluster-management.io_policies.yaml
test/e2e/case15_dep_crd_validation_test.go
test/resources/case15_dep_crd_validation/basic-policy.yaml

It is invalid to set a namespace on dependencies from our known types (ConfigurationPolicy, IamPolicy, CertificatePolicy), because those will be in the clusternamespace on the managed cluster.

Add CRD validation for namespaces in dependencies

---

Makefile
deploy/crds/policy.open-cluster-management.io_policies.yaml

Since the CRDs are synchronized across multiple repositories, the format needs to be kept consistent.

Fix format of policy CRD yaml

---

controllers/automation/policyautomation_controller.go
test/e2e/case5_policy_automation_test.go

Still pass policy info when all clusters are compliant, just skip violation context

Only pass violation context when non compliant cluster exists

---

controllers/propagator/metric.go
controllers/propagator/policy_controller.go

This excludes a test because all failures that would trigger the metric to increment are API related and would be difficult to mock.
Relates:
https://issues.redhat.com/browse/ACM-2397

Add a metric to record policy propagation failures

---

Makefile

Some systems require `echo -e` whereas for others it doesn't work. printf works in both cases.

Use printf instead of echo for changing CRD format

---

go.mod
go.sum

Relates:
https://issues.redhat.com/browse/ACM-2449

Update kubernetes-dependency-watches to v0.1.1

---

api/v1/policy_types.go
controllers/propagator/replication_test.go
deploy/crds/kustomize/policy.open-cluster-management.io_policies.yaml
deploy/crds/policy.open-cluster-management.io_policies.yaml

Adds an enum for dependencies[].compliance and extraDependencies[].compliance to block creation of policies with that field set incorrectly. This will fix policies creating with invalid dependencies.
refs:
https://issues.redhat.com/browse/ACM-2148

Use enum for dependency compliance

---

Makefile
controllers/automation/policyautomation_controller.go
deploy/operator.yaml
deploy/rbac/role.yaml
test/e2e/case5_policy_automation_test.go
test/resources/case5_policy_automation/cluster-dns.yaml
test/resources/case5_policy_automation/dns-crd.yaml

Using the Kubernetes configuration leads to a local DNS name when running in the cluster. This commit changes it to use the OpenShift dnses custom resource to get the value. Other Kubernetes distributions could have their own implementations added later.
Relates:
https://issues.redhat.com/browse/ACM-2410

Provide the correct Hub DNS name in the Ansible extra_vars

---

api/v1beta1/policyautomation_types.go
controllers/automation/policyautomation_controller.go
deploy/crds/policy.open-cluster-management.io_policyautomations.yaml
test/e2e/case5_policy_automation_test.go

Relates:
https://issues.redhat.com/browse/ACM-2946

Use better names for the extra_vars passed to the Ansible job

---

api/v1/policy_types.go
controllers/propagator/replication.go
deploy/crds/kustomize/policy.open-cluster-management.io_policies.yaml
deploy/crds/policy.open-cluster-management.io_policies.yaml
test/e2e/case1_propagation_test.go

This new field allows a replicated policy to not have labels and annotations that are not managed by the policy framework. This is useful in the case where policies are deployed with ArgoCD and you don't want them to show up in the ArgoCD UI.
Additionally, the argocd.argoproj.io/compare-options annotation is now always set to IgnoreExtraneous on the replicated policies to avoid ArgoCD trying to manage the replicated policies.
Relates:
https://issues.redhat.com/browse/ACM-1690

Add the spec.copyPolicyMetadata field

---

controllers/propagator/propagation.go

If the policy uses templates with encryption, the desired replicated policy should not get its default annotations overridden.
Relates:
https://issues.redhat.com/browse/ACM-1690

Stop overriding default annotations when IV annotation is set

---

go.mod
go.sum

This will reduce the number of API calls for discovery.

Update the dependency watch client library

---

test/e2e/case9_templates_test.go
test/resources/case9_templates/case9-test-policy_copy.yaml
test/resources/case9_templates/case9-test-replpolicy_copied-managed1.yaml
test/resources/case9_templates/case9-test-replpolicy_copied-managed2.yaml

Adding the `copyConfigMapData` and the `copySecretData` template functions to the policy propagator.
Refs:
- https://issues.redhat.com/browse/ACM-2611

Add support for the copy template functions to the propagator

---

controllers/propagator/propagation.go
go.mod
go.sum
test/e2e/case9_templates_test.go
test/resources/case9_templates/case9-test-policy-cslookup.yaml
test/resources/case9_templates/case9-test-policy.yaml
test/resources/case9_templates/case9-test-replpolicy-managed1-relabelled.yaml
test/resources/case9_templates/case9-test-replpolicy-managed1.yaml
test/resources/case9_templates/case9-test-replpolicy-managed2.yaml

Previously, there were some inconsistencies in how a hub template lookup for a cluster-scoped resource worked. As a result, the propagator would throw an error, and not be able to populate a real status for policies that tried to use that kind of lookup.
Now, in general, using lookup in a hub template for a cluster-scoped resource will fail with a template error that can be seen in the propagated policy. The one current exception is that a lookup of the ManagedCluster where the policy is replicated is allowed.
Refs:
- https://issues.redhat.com/browse/ACM-5547

Better handling of cluster-scoped template lookups

---

.github/workflows/kind.yml
Makefile
PROJECT
README.md
api/v1/policy_webhook.go
deploy/manager/manager.yaml
deploy/operator.yaml
deploy/webhook.yaml
main.go
main_test.go
test/e2e/case17_policy_webhook_test.go
test/resources/case17_policy_webhook/case17_policy_long.yaml
test/resources/case17_policy_webhook/case17_policy_replicate.yaml

Description: No validation if name + namespace exceeds 63 characters and Policy applied via CLI or Gitops now
After fix: `Error from server (Forbidden): error when creating "policy.yaml": admission webhook "policy.open-cluster-management.io.webhook" denied the request: the combined length of namespace and policy name (namespaceName.policyName) should not exceed 63 characters`
This error message shows on terminal when policy name + namespace exceeds 63 characters
Ref: https://issues.redhat.com/browse/ACM-4394

Webhook to check name + namespace exceeds 63 characters

---

api/v1/policy_webhook.go
test/e2e/case17_policy_webhook_test.go

Description: Change error message "the combined length of the policy namespace and name <namespace>.<name> cannot exceed 63 characters" to the combined length of the policy namespace and name <namespace>.<name> cannot exceed 62 characters
Ref: https://issues.redhat.com/browse/ACM-6838

Change Error message namespace + policy names

---

controllers/propagator/policy_controller.go
controllers/propagator/propagation.go
test/e2e/case1_propagation_test.go
test/utils/utils.go

Currently the propagator performs a double reconcile when the root policy is disabled, which leads to duplicated events being created. The work-around to prevent the aforementioned duplicated events is to check for the existence of replicated policies in the managed cluster namespaces. When the root policy is disabled, the first reconcile will remove the replicated policies and on the second reconcile a new check is now added to determine the existence of replicated policies, which allow the controller to safely skip over the logic that emits the second duplicated event.
ref: https://issues.redhat.com/browse/ACM-6122

Fix duplicated event generation when root policy is disabled

---

controllers/propagator/replicatedpolicy_controller.go

Fixes issues noticed by [CI run in stolostron](https://github.com/stolostron/governance-policy-propagator/pull/459), but not here. In particular, an issue identified by SonarCloud, and an issue with hosted mode clusters.

Ignore synced policies for hosted clusters

---

controllers/propagator/encryption.go
controllers/propagator/encryption_test.go
controllers/propagator/propagation.go
controllers/propagator/replicatedpolicy_controller.go
controllers/propagator/replicatedpolicy_setup.go
go.mod
go.sum
main.go

This leverages the new caching functionality in go-template-utils so that API queries are not duplicated.
As a side-effect, this should cause less reconciles because when starting a watch due to a hub template, it does not cause an initial reconcile merely from the watch being created.
Relates:
https://issues.redhat.com/browse/ACM-7402
https://issues.redhat.com/browse/ACM-7398

Cache hub template queries

---

controllers/common/policyset_handler.go
controllers/propagator/rootpolicy_setup.go

Currently, a reconcile request is made for every single policy in the policy set on update. A custom event handler was added to only reconcile the differing policies between the new and old policy sets. `policySetPredicateFuncs` was also removed, and the logic was added to the `policySetMapper` function.
Ref: https://issues.redhat.com/browse/ACM-7397

ACM-7397: Reduce the reconciles caused from policy set updates

---

controllers/rootpolicystatus/root_policy_status_controller.go

When it is in hosted mode, root_status_controller loops because of the replicated policy.  replicated policies in hosted are not filtered because namespace is not in managedcluster.

[Hotfix]Filter replicated policy in rootstatus ctlr

---

api/v1/policy_webhook.go
deploy/webhook.yaml
test/e2e/case17_policy_webhook_test.go
test/resources/case17_policy_webhook/case17_invalid_remediation_policy.yaml
test/resources/case17_policy_webhook/case17_valid_remediation_policy_cfplc.yaml
test/resources/case17_policy_webhook/case17_valid_remediation_policy_root.yaml

Currently, when the remediationAction field is unset in both the root policy and configuration policy in its policy template, the violation is generated as an event by the config-policy controller in the managed cluster.
This PR addresses the issue by updating the validating webhook so that the violation can be caught on policy creation and updates on the hub.
ref: https://issues.redhat.com/browse/ACM-7551

Update the webhook to validate the remediationAction field of policies

---

.github/workflows/kind.yml
Makefile
test/e2e/case5_policy_automation_test.go

The PolicyAutomation tests were taking about half of the total e2e test duration. This excludes those tests from the usual `make e2e-test` target, which will accelerate both the CI and local development. Those tests are now run in a separate (concurrent) GH job in the CI workflow, and the test coverage information is merged in another new job.
This also combines the unit tests and linting tasks into one job, which means that a linting or formatting error will not prevent the e2e tests from running.
Refs:
- https://issues.redhat.com/browse/ACM-8239

Run PolicyAutomation tests separately in CI

---

.github/workflows/kind.yml
Makefile
deploy/manager/kustomization.yaml
deploy/manager/manager.yaml
deploy/manager/service-account.yaml
test/e2e/case10_policyset_propagation_test.go
test/e2e/case11_policyset_controller_test.go
test/e2e/case12_encryptionkeys_controller_test.go
test/e2e/case13_policyset_dependencies_test.go
test/e2e/case14_root_policy_metrics_test.go
test/e2e/case16_selective_policy_enforcement_test.go
test/e2e/case17_policy_webhook_test.go
test/e2e/case19_rep_policy_placement_test.go
test/e2e/case1_propagation_test.go
test/e2e/case2_aggregation_test.go
test/e2e/case3_mutation_recovery_test.go
test/e2e/case4_unexpected_policy_test.go
test/e2e/case5_policy_automation_test.go
test/e2e/case6_placement_propagation_test.go
test/e2e/case7_bindings_test.go
test/e2e/case8_metrics_test.go
test/e2e/case9_templates_test.go
test/e2e/e2e_suite_test.go
test/resources/e2e_controller_secret.yaml

Previously, the E2E tests on PRs did not use ServiceAccounts, requiring manual updates for permissions for a code change. This change instead uses ServiceAccounts generated by Kubebuilder.
Ref: https://issues.redhat.com/browse/ACM-3299

ACM-3299: governance-policy-propagator: Use SA for E2E

---

.gitignore
Makefile
controllers/common/common_status_update.go
controllers/propagator/propagation.go
controllers/propagator/rootpolicy_controller.go

Also:
- Add `e2e-test-coverage-foreground` target
- Add kubeconfig to `.gitignore`
- Skip `GuttedObject` for generation (This was resulting in an empty `_.yaml` CRD file being generated)

Drop `ClusterNamespace` internally to prep for Placement

---

controllers/complianceeventsapi/server.go
controllers/complianceeventsapi/types.go

To allow stolostron CI to pass (we should probably bring this gosec scan into open-cluster-management-io...)

Add gosec annotations for sha1 usage

---

controllers/complianceeventsapi/migrations/000001_compliance_history_initial_tables.up.sql
controllers/complianceeventsapi/server.go
controllers/complianceeventsapi/types.go
controllers/complianceeventsapi/types_test.go
test/e2e/case18_compliance_api_test.go

Rather than provide spec_hash, the POST endpoint now accepts a parent
policy ID and/or policy ID. This saves on network bandwidth and resource
utilization when the ID is known.
This also changes spec to be JSONB instead of a JSON string. This allows
a unique constraint without serializing it in a special way with map
keys sorted.
There is also a fix in the select queries with dealing with null values. `= NULL` is always false and what we want is `IS NULL`.
The first commit sets the primary key types to int32 to match the Postgres serial primary key option of values 1 to 2147483647.

Remove spec_hash and allow the use of IDs instead

---

Makefile
controllers/propagator/replicatedpolicy_controller.go

- Add back propagation/update events
- Also updates `make run` so that it works (since the webhook had to be disabled).
ref: https://issues.redhat.com/browse/ACM-9461

Add back propagation/update events

---

controllers/complianceeventsapi/types.go
controllers/propagator/replicatedpolicy_controller.go
controllers/propagator/replicatedpolicy_controller_test.go
test/e2e/case14_root_policy_metrics_test.go
test/e2e/case1_propagation_test.go
test/e2e/case20_compliance_api_controller_test.go
test/e2e/case3_mutation_recovery_test.go
test/e2e/case6_placement_propagation_test.go
test/e2e/case9_templates_test.go
test/utils/utils.go

This was also incorrectly setting the replicated policy annotations on the policy template's annotations.
Built from #174

Fix spec fetching for Compliance API

---

.gitignore
Makefile
build/common/Makefile.common.mk
build/kind/postgres.yaml
controllers/complianceeventsapi/auth.go
controllers/complianceeventsapi/auth_test.go
controllers/complianceeventsapi/complianceeventsapi_controller.go
controllers/complianceeventsapi/server.go
deploy/manager/manager.yaml
deploy/operator.yaml
deploy/rbac/role.yaml
go.mod
go.sum
main.go
main_test.go
test/e2e/case18_compliance_api_test.go
test/e2e/case20_compliance_api_controller_test.go

If a certificate is provided, the HTTP server will run over HTTPS which enables certificate authentication.
The authorization requires a user to have patch access to the policy status on the managed cluster namespace of the managed cluster that the compliance event is for.
Relates:
https://issues.redhat.com/browse/ACM-6866

Add certificate and token auth and authz on the POST API endpoint

---

controllers/complianceeventsapi/server.go
controllers/complianceeventsapi/server_test.go
test/e2e/case18_compliance_api_test.go

Generating a report as described in the [design](https://github.com/open-cluster-management-io/enhancements/tree/main/enhancements/sig-policy/98-long-term-compliance-history#generating-a-report).
Ref: https://issues.redhat.com/browse/ACM-6884

Add an API endpoint to generate a CSV compliance report

---

controllers/common/common.go
controllers/common/common_status_update.go
test/e2e/case2_aggregation_test.go
test/resources/case2_aggregation/faulty-placementbinding.yaml

With a `PlacementBinding` containing an invalid `placementRef`, the propagator was returning an error and endlessly re-reconciling. This occurs even if the `PlacementBinding` was not bound to the Policy.
Also swaps the namespace and name in the message because it was non-standard.
ref: https://issues.redhat.com/browse/ACM-9930

Fix status update with faulty PlacementBinding

---

controllers/complianceeventsapi/auth.go
controllers/complianceeventsapi/server.go
main.go

This is the default way to set the CA when running in a cluster.
Relates:
https://issues.redhat.com/browse/ACM-6866

Add support for client auth CA from a file

---

controllers/complianceeventsapi/complianceeventsapi_controller.go
controllers/complianceeventsapi/server.go

This resulted in a log message every 30 seconds when the DB connection URL was unset.
The second commit filters out connection reset logs from the OpenShift router.

Stop trying to connect to the DB when the connection URL is not set

---

test/e2e/case10_policyset_propagation_test.go
test/e2e/case11_policyset_controller_test.go
test/e2e/case12_encryptionkeys_controller_test.go
test/e2e/case14_root_policy_metrics_test.go
test/e2e/case17_policy_webhook_test.go
test/e2e/case19_rep_policy_placement_test.go
test/e2e/case1_propagation_test.go
test/e2e/case20_compliance_api_controller_test.go
test/e2e/case3_mutation_recovery_test.go
test/e2e/case4_unexpected_policy_test.go
test/e2e/case5_policy_automation_test.go
test/e2e/case6_placement_propagation_test.go
test/e2e/case7_bindings_test.go
test/e2e/case8_metrics_test.go
test/e2e/case9_templates_test.go
test/e2e/e2e_suite_test.go

...because unnecessary package-level variables are a no-no.

Use testcase-scoped variables

---

test/utils/utils.go

Also adjusts `KubectlWithOutput()` so that the `stderr` message is returned with the error, rather than the unhelpful "exit status 1" system error.

Use `HaveOccurred()` for E2E error checking

---

.github/workflows/kind.yml
Makefile
controllers/complianceeventsapi/auth.go
controllers/complianceeventsapi/server.go
go.mod
go.sum
test/e2e/case18_compliance_api_test.go
test/e2e/case19_rep_policy_placement_test.go
test/e2e/case20_compliance_api_controller_test.go
test/resources/case18_compliance_api_test/subset_service_account.yaml
test/resources/case18_compliance_api_test/wrong_service_account.yaml
test/resources/managed4-cluster.yaml
test/resources/managed5-cluster.yaml
test/resources/managed6-cluster.yaml

I need to ensure that the compliance history can only be written by authorized service accounts and viewed by users with appropriate ACM access. 
**Definition of Done for Engineering Story Owner (Checklist)**
- The read API endpoint is restricted based on a user's "get" access to corresponding ManagedCluster objects. This result will filter the requests returned in the SQL queries.
Ref: https://issues.redhat.com/browse/ACM-6866
Signed-off-by: Yi Rae Kim <yikim@redhat.com>

Add authorization to the compliance event API endpoints

---

controllers/complianceeventsapi/auth.go
controllers/complianceeventsapi/server.go
go.mod
go.sum
main.go
test/e2e/case18_compliance_api_test.go
test/e2e/case20_compliance_api_controller_test.go

This will not be used and it didn't work on OpenShift because the CAs included in the Kubeconfig don't include the CA that signed the client certificate. This would have required additional code to pull the correct CA.

Remove client certificate authentication

---

main.go

Relates:
https://issues.redhat.com/browse/ACM-10066

Use the pod's namespace for the database secret when not overridden

---

controllers/complianceeventsapi/complianceeventsapi_controller.go
controllers/complianceeventsapi/server.go
controllers/complianceeventsapi/types.go
test/e2e/case20_compliance_api_controller_test.go

This resets the database ID cache whenever the database connection URL changes or an invalid cache entry is found. This also combines the database ID caches on the propagator reconciler and the compliance history API goroutines.
Relates:
https://issues.redhat.com/browse/ACM-10109

Reset the database ID cache when applicable

---

go.mod
go.sum
test/resources/case18_compliance_api_test/wrong_service_account.yaml

SelfSubjectRulesReview errantly considered role bindings in the default namespace for cluster scoped access. A namespace is required for SelfSubjectRulesReview, so a completely invalid namespace is provided to avoid this. rbac-api-utils was updated to do this by default.
Relates:
https://issues.redhat.com/browse/ACM-10162

Ignore role bindings in default namespace for RBAC

---

Makefile
controllers/complianceeventsapi/complianceeventsapi_controller.go
controllers/complianceeventsapi/server.go
controllers/complianceeventsapi/types.go
controllers/propagator/replicatedpolicy_controller.go
controllers/propagator/replicatedpolicy_controller_test.go
main.go
test/e2e/case18_compliance_api_test.go
test/e2e/case20_compliance_api_controller_test.go
test/e2e/e2e_suite_test.go
test/resources/local-cluster.yaml

The spec-sync controller is responsible for generating this event ordinarily, however, since the spec-sync does not run on self-managed hubs, it will not generate the disabled event. The Propagator must step in to do so.
The approach taken in this commit is resilient to temporary database outages.
The "Adds the database IDs by using the cache" test was removed because it was errantly reporting as passing due to it deleting the root policy and not the replicated policy as intended. There is no way to get this test to work without going to extreme lengths after 9a641148a6badf022d96e037ac3c7c4b9f726388 since it wipes the database ID cache when the secret changes. The secret was updated to something invalid to cause a database outage. Other attempts such as deleting the Service did not work …

Generate a disabled compliance history API entry for local-cluster

---

controllers/complianceeventsapi/server.go
test/e2e/case18_compliance_api_test.go

This sends a chunk every 100 lines of CSV.

Fix chunked transfers with the CSV reports

---

controllers/complianceeventsapi/migrations/000002_compliance_history_fix_indices.down.sql
controllers/complianceeventsapi/migrations/000002_compliance_history_fix_indices.up.sql
controllers/complianceeventsapi/server.go
controllers/complianceeventsapi/types.go
test/e2e/case18_compliance_api_test.go

Design document change:
https://github.com/open-cluster-management-io/enhancements/pull/113
A Postgres unique constraint fails if the spec or message is too large. The solution was to split out the spec to a separate table and include a hash of the message that the unique constraint is on.
Relates:
https://issues.redhat.com/browse/ACM-10794

Fix index errors for large values

---

api/v1/placementbinding_types.go
api/v1/policy_types.go
api/v1/zz_generated.deepcopy.go
api/v1beta1/policyautomation_types.go
api/v1beta1/policyset_types.go
controllers/policyset/policyset_controller.go
deploy/crds/kustomize/policy.open-cluster-management.io_policies.yaml
deploy/crds/policy.open-cluster-management.io_placementbindings.yaml
deploy/crds/policy.open-cluster-management.io_policies.yaml
deploy/crds/policy.open-cluster-management.io_policyautomations.yaml
deploy/crds/policy.open-cluster-management.io_policysets.yaml

ref: https://issues.redhat.com/browse/ACM-8992
I came up with my own linting rules as I went, mainly separating the descriptions from the kubebuilder tags with an empty comment line and also structuring the structs so that the "parent" structs are at the bottom of the file. I also discovered a lack of `omitempty` actually makes the field required, so the "required" tags aren't actually necessary unless `omitempty` is present, which is why those are removed but the CRD didn't change.
I also mashed the changes into a single commit because there wasn't really a great way to tease the changes apart. A review is probably easier by opening up the individual file (particularly the resulting CRD YAML) rather than looking at the changes made.
/cc @dockerymick @mprahl @gparvin @yiraeChristineKim

Update CRD descriptions

---

controllers/complianceeventsapi/complianceeventsapi_controller.go
controllers/complianceeventsapi/server.go
controllers/complianceeventsapi/types.go
controllers/propagator/replicatedpolicy_controller.go
test/e2e/case20_compliance_api_controller_test.go

This is now handled in the governance-policy-framework-addon: https://github.com/open-cluster-management-io/governance-policy-framework-addon/pull/132
Relates:
https://issues.redhat.com/browse/ACM-10418

Remove the code to generate disabled compliance events for local-cluster

---

controllers/propagator/propagation.go

The framework-addon will handle the reporting of the hub template errors, it is not necessary for each controller to consider them.
Refs:
- https://issues.redhat.com/browse/ACM-10858

Allow all policy types to use hub templates

---

Makefile

The controller and service references wouldn't work otherwise.

Fix deployments for alternate namespaces

---

controllers/common/common_status_update.go

These log messages can get quite noisy and cause important logs to be lost during support cases.
Relates:
https://issues.redhat.com/browse/ACM-12447

Reduce the log level for a noisy log

---

controllers/propagator/propagation.go

This happened in a PR CI failure where the watch was stopped and started again quickly before the watch was fully stopped.
https://github.com/stolostron/governance-policy-propagator/actions/runs/9764716738/job/26953706058?pr=773

Retry template processing when k8s dep watcher is stopping a watch

---

.github/workflows/kind.yml
Makefile
controllers/policyset/policyset_controller.go
controllers/propagator/replicatedpolicy_setup.go
controllers/rootpolicystatus/root_policy_status_controller.go
main.go
test/e2e/case4_unexpected_policy_test.go

Some deployments will not want to install the PlacementRule CRD, since it is an older API which may eventually be removed. This adds an argument to the propagator which will disable all watches on PlacementRules, allowing the controllers to run in those environments.
In addition, if the flag is not set, the controller will check for the PlacementRule CRD on the cluster, and if not found, disable those watches (which would otherwise fail and prevent the controller from working).
Refs:
- https://issues.redhat.com/browse/ACM-2609

Add flag to disable PlacementRule watches

---

Makefile
deploy/crds/policy.open-cluster-management.io_policies.yaml

Related to:
- https://github.com/open-cluster-management-io/governance-policy-addon-controller/pull/168

Make CRD descriptions folded

---

controllers/propagator/propagation.go
go.mod
go.sum
test/resources/case9_templates/case9-test-policy.yaml
test/resources/case9_templates/case9-test-replpolicy-managed1-relabelled.yaml
test/resources/case9_templates/case9-test-replpolicy-managed1.yaml
test/resources/case9_templates/case9-test-replpolicy-managed2.yaml

This is a subset of the root policy metadata. Specifically, it contains, name, namespace, labels, and annotations.
Relates:
https://issues.redhat.com/browse/ACM-12566

Add the PolicyMetadata hub template variable

---

Makefile
build/Dockerfile
go.mod

ref: https://issues.redhat.com/browse/ACM-14251

Update to Go v1.22

---

controllers/propagator/replication.go
controllers/propagator/replication_test.go

There was an assumption a dot in a name meant it contained the namespace. But this doesn't make sense if the namespace is also provided.
ref: https://issues.redhat.com/browse/ACM-14241

Fix dependency logic considering dots in names

---

api/v1/policy_types.go
deploy/crds/kustomize/policy.open-cluster-management.io_policies.yaml
deploy/crds/policy.open-cluster-management.io_policies.yaml

Relates:
https://issues.redhat.com/browse/ACM-13572

Document the spec.hubTemplateOptions.serviceAccountName field

---

.github/workflows/kind.yml
api/v1/policy_webhook.go

Replace usage of deprecated `webhook.Validator` interface with `admission.CustomValidator`.

Fix usage of deprecated webhook.Validator interface
